export const CARD_TYPES = {
    CHANCE: 'CHANCE',
    COMMUNITY_CHEST: 'COMMUNITY_CHEST'
};

export const CARD_ACTIONS = {
    MOVE_TO: 'MOVE_TO',
    CASH_MODIFIER: 'CASH_MODIFIER',
    JAIL_RELEASE: 'JAIL_RELEASE',
    GO_TO_JAIL: 'GO_TO_JAIL',
    ASSESS_REPAIRS: 'ASSESS_REPAIRS'
};